databases:
  - name: sweet-shop-db
    databaseName: sweetshop
    user: sweetshop_user
    plan: free

services:
  - type: web
    name: sweet-shop-backend
    runtime: docker
    plan: free
    rootDir: backend
    startCommand: "python manage.py migrate && gunicorn api.wsgi:application --bind 0.0.0.0:$PORT"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sweet-shop-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DB_SCHEMA
        value: public
